[toolchain]
package_manager = "yarn"
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
perpe = "perpmwcaoweY2WNxviUKrJPCAvLaNHGESXZGZgiDVDS"

[programs.devnet]
perpe = "perpmwcaoweY2WNxviUKrJPCAvLaNHGESXZGZgiDVDS"

[programs.mainnet]
perpe = "perpmwcaoweY2WNxviUKrJPCAvLaNHGESXZGZgiDVDS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/root/perp-dev.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

